# -*- coding: utf-8 -*-
"""Codigo_Sagemaker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14J8lmcbQrHKyEbzJP-VVwiF_fGm6JuMp
"""

from sagemaker.canvas.estimators import BlazingText
import pandas as pd

# Carregar os dados de estoque
data = pd.read_csv('estoque.csv')

# Realizar a limpeza dos dados (remover valores nulos, outliers, etc.)
data_cleaned = data.dropna()


# Definir e treinar o modelo de previsão de estoque
model = BlazingText(role='role_arn', instance_count=1, instance_type='ml.m4.xlarge')
model.fit(data_cleaned)

# Avaliar a precisão do modelo utilizando métricas adequadas
accuracy = model.evaluate(data_cleaned)

# Implantar o modelo em um endpoint para a previsão em tempo real
endpoint = model.deploy(instance_type='ml.t2.medium')